#
curlCommand: /opt/local/bin/curl -L -s
curlCommand: /usr/bin/curl -L -s
#
gzipCommand: /opt/local/bin/gzip
#gzipCommand: /bin/gzip
#
rmCommand: /bin/rm
#
tarCommand: /usr/bin/tar
#tarCommand: /bin/tar
#
#noaaDir: /vocal-seagull-aws/noaa
noaaDir: /Users/gsc/IdeaProjects/vocal-seagull-aws/noaa
#
#rootDir: /vocal-seagull-aws
rootDir: /Users/gsc/IdeaProjects/vocal-seagull-aws
#
seagullPath: /var/vocal/seagull
#
mySqlUserName: seagull
mySqlPassWord: bogus
mySqlDataBase: vocal_seagull
mySqlHostName: localhost
#
awsAccessKey: bogus
awsSecretKey: bogus
#