#
curlCommand: /usr/bin/curl -L -s
#
gzipCommand: /bin/gzip
#
rmCommand: /bin/rm
#
tarCommand: /bin/tar
#
exportDir: /var/vocal/seagull/export
#
importDir: /var/vocal/seagull/import
#
noaaDir: noaa
#
dbUserName: seagull
dbPassWord: bogus
dbDataBase: vocal_seagull
dbHostName: localhost
#
