#
curlCommand: /usr/bin/curl -L -s
#
gzipCommand: /bin/gzip
#
rmCommand: /bin/rm
#
tarCommand: /bin/tar
#
exportDir: /var/vocal/seagull/export
#
noaaDir: /var/vocal/seagull/export/noaa
#
mySqlUserName: seagull
mySqlPassWord: bogus
mySqlDataBase: vocal_seagull
mySqlHostName: localhost
#
