#
curlCommand: /usr/bin/curl -L -s
#
gzipCommand: /bin/gzip
#
rmCommand: /bin/rm
#
tarCommand: /bin/tar
#
exportDir: /vocal-seagull-aws/seagull/export
#
importDir: /vocal-seagull-aws/seagull/import
#
noaaDir: noaa
#
mySqlUserName: seagull
mySqlPassWord: bogus
mySqlDataBase: vocal_seagull
mySqlHostName: localhost
#
